// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: pb/downloadcache.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the URL and an invalidation flag.
type DownloadCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Invalidate bool   `protobuf:"varint,2,opt,name=invalidate,proto3" json:"invalidate,omitempty"`
}

func (x *DownloadCacheRequest) Reset() {
	*x = DownloadCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_downloadcache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadCacheRequest) ProtoMessage() {}

func (x *DownloadCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_downloadcache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadCacheRequest.ProtoReflect.Descriptor instead.
func (*DownloadCacheRequest) Descriptor() ([]byte, []int) {
	return file_pb_downloadcache_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadCacheRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadCacheRequest) GetInvalidate() bool {
	if x != nil {
		return x.Invalidate
	}
	return false
}

// The response message containing the page contents.
type DownloadCacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageContents string `protobuf:"bytes,1,opt,name=page_contents,json=pageContents,proto3" json:"page_contents,omitempty"`
}

func (x *DownloadCacheResponse) Reset() {
	*x = DownloadCacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_downloadcache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadCacheResponse) ProtoMessage() {}

func (x *DownloadCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_downloadcache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadCacheResponse.ProtoReflect.Descriptor instead.
func (*DownloadCacheResponse) Descriptor() ([]byte, []int) {
	return file_pb_downloadcache_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadCacheResponse) GetPageContents() string {
	if x != nil {
		return x.PageContents
	}
	return ""
}

var File_pb_downloadcache_proto protoreflect.FileDescriptor

var file_pb_downloadcache_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x63, 0x68, 0x65, 0x22, 0x48, 0x0a, 0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x22, 0x3c, 0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x70, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x32,
	0x61, 0x0a, 0x0d, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x12, 0x50, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x23, 0x2e, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x79, 0x6f, 0x75, 0x72, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x2f, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_downloadcache_proto_rawDescOnce sync.Once
	file_pb_downloadcache_proto_rawDescData = file_pb_downloadcache_proto_rawDesc
)

func file_pb_downloadcache_proto_rawDescGZIP() []byte {
	file_pb_downloadcache_proto_rawDescOnce.Do(func() {
		file_pb_downloadcache_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_downloadcache_proto_rawDescData)
	})
	return file_pb_downloadcache_proto_rawDescData
}

var file_pb_downloadcache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_downloadcache_proto_goTypes = []interface{}{
	(*DownloadCacheRequest)(nil),  // 0: downloadcache.DownloadCacheRequest
	(*DownloadCacheResponse)(nil), // 1: downloadcache.DownloadCacheResponse
}
var file_pb_downloadcache_proto_depIdxs = []int32{
	0, // 0: downloadcache.DownloadCache.Get:input_type -> downloadcache.DownloadCacheRequest
	1, // 1: downloadcache.DownloadCache.Get:output_type -> downloadcache.DownloadCacheResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_downloadcache_proto_init() }
func file_pb_downloadcache_proto_init() {
	if File_pb_downloadcache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_downloadcache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_downloadcache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadCacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_downloadcache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_downloadcache_proto_goTypes,
		DependencyIndexes: file_pb_downloadcache_proto_depIdxs,
		MessageInfos:      file_pb_downloadcache_proto_msgTypes,
	}.Build()
	File_pb_downloadcache_proto = out.File
	file_pb_downloadcache_proto_rawDesc = nil
	file_pb_downloadcache_proto_goTypes = nil
	file_pb_downloadcache_proto_depIdxs = nil
}
